### ISSUE TITLE
PR into develop

### ISSUE THREAD

**Issue by Vavat** [Niuslar/Multichannel-Temperature-Control#46]
@Niuslar, please modify the rules for the PR merge to have a successful pipeline build. This should be fairly obvious. Let me or @FrozenOxide  know if you cannot find it.

**Comment by Niuslar** [comment]
@Vavat, @Masitech I added a rule to require a successful build in order to merge. Please let me know if this is what you meant.  
![image](https://user-images.githubusercontent.com/34103285/161518222-9d2ecdeb-d55d-4e7c-aeed-06fd73251f97.png)

**Comment by MAhmedDev** [comment]
Looks awesome, nice work 👍
