### ISSUE TITLE
Add this to ReadMe

### ISSUE THREAD

**Issue by Niuslar** [Niuslar/Multichannel-Temperature-Control#76]
To use pins PA2 and PA3 as USART2, we need the following: SB62 and SB63 must be ON, while SB13 and SB14 must be OFF.

**Comment by Vavat** [comment]
@Niuslar, is this issue active or should it be closed? It wasn't in the project, so I wasn't sure if it should be active.

**Comment by Niuslar** [comment]
It still applies if we want to use USART2 without ST-LINK. Since we're using USART1 I think this can be closed.
