### ISSUE TITLE
Messages in CTemperatureController::sendStatus() are too long

### ISSUE THREAD

**Issue by Niuslar** [Niuslar/Multichannel-Temperature-Control#89]
The max size for a UART message is 60 characters. 
sendStatus() loops throught the channels and appends the value to the message, 
this is causing the message to be truncated. 
One option is to send each channel's data in a separate message/line. 
Another option is to increase the max. size in CUartCom and the `etl::string<MAX_STRING_SIZE> message` variable.

**Comment by Niuslar** [comment]
@Vavat Let me know which option you prefer. If it is to change the UART class I can take care of it. If not I'll let you fix the temperature controller.

**Comment by Vavat** [comment]
set `MAX_STRING_SIZE` TO 150.
